# Generated by Django 5.1.1 on 2024-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botcontrol',
            old_name='expiration_date',
            new_name='expiration_month',
        ),
        migrations.AddField(
            model_name='botcontrol',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
