# Generated by Django 5.1.1 on 2024-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_expiration_date_botcontrol_expiration_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
