# Generated by Django 5.1.1 on 2024-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_botcontrol_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'KmzK0qEVA5TzcvmHrpWEGK57yAoY42MpfdsTSyJQjRo=', max_length=255, null=True),
        ),
    ]
