# Generated by Django 5.1.1 on 2024-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_botcontrol_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'Gn4gmA1if8uGnIOr8-0mOadFwC3HQV_4qYV0tcfYXuU=', max_length=255, null=True),
        ),
    ]
