# Generated by Django 5.1.1 on 2024-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_botcontrol_card_type_alter_botcontrol_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaxPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'bxgWQlkdQIatBrnKR02hTU_tLfaOiTblx9eiGCZlWvo=', max_length=255, null=True),
        ),
    ]
