# Generated by Django 5.1.1 on 2024-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_productmaxprice_alter_botcontrol_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaxprice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaxprice',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'ovkjWAZfi5DNgvo-VDWDr_rWTZag5sZp0zt0yN-59GA=', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmaxprice',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
