# Generated by Django 5.1.1 on 2024-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_productmaxprice_date_productmaxprice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontrol',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'zD_IRGWyffo7BsUtaybeBlsNBpeSjG_cgtWe5m7tKpE=', max_length=255, null=True),
        ),
    ]
