# Generated by Django 5.1.1 on 2024-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_botcontrol_card_type_alter_botcontrol_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontrol',
            name='key',
            field=models.CharField(blank=True, default=b'bIaOYbsHU9M3zhsnr40ShQmwhGwKhgBU1nnAnNP3KhE=', max_length=255, null=True),
        ),
    ]
